_url_regex = r'''(?i)\b((?:https?:(?:/{1,3}|[a-z0-9%])|[a-z0-9.\-]+[.](?:com|net|org|edu|gov|mil|aero|asia|biz|cat|coop|info|int|jobs|mobi|museum|name|post|pro|tel|travel|xxx|ac|ad|ae|af|ag|ai|al|am|an|ao|aq|ar|as|at|au|aw|ax|az|ba|bb|bd|be|bf|bg|bh|bi|bj|bm|bn|bo|br|bs|bt|bv|bw|by|bz|ca|cc|cd|cf|cg|ch|ci|ck|cl|cm|cn|co|cr|cs|cu|cv|cx|cy|cz|dd|de|dj|dk|dm|do|dz|ec|ee|eg|eh|er|es|et|eu|fi|fj|fk|fm|fo|fr|ga|gb|gd|ge|gf|gg|gh|gi|gl|gm|gn|gp|gq|gr|gs|gt|gu|gw|gy|hk|hm|hn|hr|ht|hu|id|ie|il|im|in|io|iq|ir|is|it|je|jm|jo|jp|ke|kg|kh|ki|km|kn|kp|kr|kw|ky|kz|la|lb|lc|li|lk|lr|ls|lt|lu|lv|ly|ma|mc|md|me|mg|mh|mk|ml|mm|mn|mo|mp|mq|mr|ms|mt|mu|mv|mw|mx|my|mz|na|nc|ne|nf|ng|ni|nl|no|np|nr|nu|nz|om|pa|pe|pf|pg|ph|pk|pl|pm|pn|pr|ps|pt|pw|py|qa|re|ro|rs|ru|rw|sa|sb|sc|sd|se|sg|sh|si|sj|Ja|sk|sl|sm|sn|so|sr|ss|st|su|sv|sx|sy|sz|tc|td|tf|tg|th|tj|tk|tl|tm|tn|to|tp|tr|tt|tv|tw|tz|ua|ug|uk|us|uy|uz|va|vc|ve|vg|vi|vn|vu|wf|ws|ye|yt|yu|za|zm|zw)/)(?:[^\s()<>{}\[\]]+|\([^\s()]*?\([^\s()]+\)[^\s()]*?\)|\([^\s]+?\))+(?:\([^\s()]*?\([^\s()]+\)[^\s()]*?\)|\([^\s]+?\)|[^\s`!()\[\]{};:'".,<>?«»“”‘’])|(?:(?<!@)[a-z0-9]+(?:[.\-][a-z0-9]+)*[.](?:com|net|org|edu|gov|mil|aero|asia|biz|cat|coop|info|int|jobs|mobi|museum|name|post|pro|tel|travel|xxx|ac|ad|ae|af|ag|ai|al|am|an|ao|aq|ar|as|at|au|aw|ax|az|ba|bb|bd|be|bf|bg|bh|bi|bj|bm|bn|bo|br|bs|bt|bv|bw|by|bz|ca|cc|cd|cf|cg|ch|ci|ck|cl|cm|cn|co|cr|cs|cu|cv|cx|cy|cz|dd|de|dj|dk|dm|do|dz|ec|ee|eg|eh|er|es|et|eu|fi|fj|fk|fm|fo|fr|ga|gb|gd|ge|gf|gg|gh|gi|gl|gm|gn|gp|gq|gr|gs|gt|gu|gw|gy|hk|hm|hn|hr|ht|hu|id|ie|il|im|in|io|iq|ir|is|it|je|jm|jo|jp|ke|kg|kh|ki|km|kn|kp|kr|kw|ky|kz|la|lb|lc|li|lk|lr|ls|lt|lu|lv|ly|ma|mc|md|me|mg|mh|mk|ml|mm|mn|mo|mp|mq|mr|ms|mt|mu|mv|mw|mx|my|mz|na|nc|ne|nf|ng|ni|nl|no|np|nr|nu|nz|om|pa|pe|pf|pg|ph|pk|pl|pm|pn|pr|ps|pt|pw|py|qa|re|ro|rs|ru|rw|sa|sb|sc|sd|se|sg|sh|si|sj|Ja|sk|sl|sm|sn|so|sr|ss|st|su|sv|sx|sy|sz|tc|td|tf|tg|th|tj|tk|tl|tm|tn|to|tp|tr|tt|tv|tw|tz|ua|ug|uk|us|uy|uz|va|vc|ve|vg|vi|vn|vu|wf|ws|ye|yt|yu|za|zm|zw)\b/?(?!@)))'''

_regex_token = \
   [(_url_regex, ' <LINK> '),
    ('[\U0001f000-\U0001ffff]', ''),
    (u'[\u2764\ufe0f]+', ' <3 '),
    (r'\n', ' '),
    (r'\w\. ', ' \. '),
    (r'\.{2,}', ' <...> '),
    (r'\,', ' , '),
    (r'\?+', ' ? '),
    (r'\!+', ' ! '),
    (r'\*+', ' * '),
    (r'[\(\)]', ''),
    (r'[\"\']+', ''),
    (r'\:', ' \\ '),
    (r' q ', ' que '),
    (r'(k{3,})', ' <LAUGH> '), 
    (r'(h[aeiouh]+.*){2,}', ' <LAUGH> '), 
    (r'([aeiou]+.*h+){2,}', ' <LAUGH> '),
    (r' l+o+l+ ', ' <LAUGH> '), 
    (r' j{3,} ', ' <LAUGH> '),
    (r' ma+n+o+ ', ' mano '),
    (r' m+a+s{2,}a+ ', ' massa '),
    (r' ma+luco ', ' maluco '),
    (r' ma+s+ ', ' mas '),
    (r' ma+i+ ', ' mas '),
    (r' ma+ta ', ' mata '),
    (r' sdds+ ', ' saudades '),
    (r' bauio ', ' bagulho '),
    (r' cabo ', ' acabou '), 
    (r'<media omitted>', ' <MEDIA> '),
    (r' hu*m* ', ' hmm '),
    (r' ae+ ', ' ae '),
    (r' kd+ ', ' cadê '),
    (r' cade ', ' cadê '), 
    (r' baum ', ' bom '),
    (r' tom+o+ ', ' tomou '),
    (r' opiniao ', ' opinião '),
    (r' marromeno ', ' mais ou menos '),
    (r' k+r+l+ ', ' caralho '),
    (r' cara+lho+ ', ' caralho '),
    (r' kralha ', ' caralha '),
    (r' kra+i+o+ ', ' caralho '),
    (r' preu ', ' pra eu '),
    (r' adimitir ', ' admitir '),
    (r' hitoria ', ' história '), 
    (r' estomago ', ' estômago '),
    (r' v[ée]+i+ ', ' velho '), 
    (r' loka ', ' louca '), 
    (r' bobera ', ' bobeira '),
    (r' ultimo ', ' último '),
    (r' jisuis ', ' jesus '),
    (r' boto+ ', ' colocou '),
    (r' msg ', ' mensagem '),
    (r' duma ', ' de uma '),
    (r' alcool ', ' álcool '),
    (r' jogá ', ' jogar '),
    (r' j+o+g+a+ ', ' joga '),
    (r' fa+z+ ', ' faz '),
    (r' f+i+c+a+ ', ' fica '),
    (r' agr ', ' agora '),
    (r' ma+n+o+ ', ' mano '),
    (r' serie ', ' série '), 
    (r' anima+va ', ' animava '),
    (r' be*be+u+ ', ' bebeu '),
    (r' be+b+e+ ', ' bebe '),
    (r' i+a ', ' ia '),
    (r' temos\.limite ', ' temos limite '),
    (r' te+m+po+ ', ' tempo '),
    (r' amanha ' , ' amanhã '),
    (r' mao ', ' mão '),
    (r' a+o+h* ', ' aô '),
    (r' jaja ', ' já já '),
    (r' poe ', ' põe '),
    (r' numero ', ' número '),
    (r' msma ', ' mesma '),
    (r' d+[áa]+ ', ' dá '),
    (r' nivel ', ' nível '),
    (r' varios ', ' vários '),
    (r' varias ', ' várias '),
    (r' i+ss+o+ ', ' isso '),
    (r' tu+do+ ', ' tudo '),
    (r' cara+i+ ', ' caralho '),
    (r' de+u+ ', ' deu '),
    (r' rapido ', ' rápido '),
    (r' [êe]+p+a+ ', ' epa '),
    (r' fico+u* ', ' ficou '),
    (r' va+m+o+ ', ' vamos '),
    (r' da+v+a+ ', ' dava '),
    (r' ja+ ', ' já '), 
    (r' remedio ', ' remédio '),
    (r' busao ', ' busão '),
    (r' gemidao ', ' gemidão '),
    (r' akele ', ' aquele '),
    (r' gnt ', ' gente '),
    (r' vô ', ' avô '),
    (r' vó ', ' avó '),
    (r' v[ãa]+o+ ', ' vão '),
    (r' relacao ', ' relação '),
    (r' td ', ' tudo '),
    (r' crio ', ' criou '),
    (r' d+e*m+a+i+s+ ', ' d+ '),
    (r' toma+ra+ ', ' tomara '),
    (r' n+a+o+i+ ', ' não '),
    (r' cari[mn]+ho ', ' carinho '),
    (r' arru+ma+ ', ' arruma '),
    (r' diacord ', ' discord '),
    (r' numa ', ' em uma '),
    (r' ti+nha+ ', ' tinha '),
    (r' negoço ', ' negócio '),
    (r' b+l+z ', ' blz '),
    (r' go+s+t+o+ ', ' gosto '),
    (r' instantâne ', ' instantâneo'),
    (r' gigant ', ' gigante '),
    (r' flando ', ' falando '),
    (r' epoca ', ' época '),
    (r' na+h+ ', ' nem '),
    (r' rapa+i ', ' rapaz '),
    (r' n[eé]+ ', ' né '),
    (r' akelas ', ' aquelas '),
    (r' akela ', ' aquela '),
    (r' horario ', ' horário '),
    (r' meudeusdoceu ', ' meu deus do céu '),
    (r' taporra ', ' eita porra '),
    (r' l+a+h+ ', ' lá '),
    (r' ateh ', ' até '), 
    (r' i+a+ ', ' ia '),
    (r' certi[mn]+ ', ' certinho '),
    (r' t+b+m+ ', ' também '), 
    (r' tambem ', ' também '), 
    (r' ma ', ' mas '),
    (r' idéia ', ' ideia '),
    (r' idea ', ' ideia '),
    (r' ta+m+o+ ', ' estamos '),
    (r' i+h+ ', ' ih '),
    (r' inagino ', ' imagino '),
    (r' vizin ' , ' vizinho '),
    (r' igualzin ', ' igualzinho '),
    (r' virjao ', ' virjão '),
    (r' dorga ', ' droga '),
    (r' vontadi ', ' vontade '),
    (r' bauzin ', ' bauzinho '),
    (r' absu+rdo+ ', ' absurdo '),
    (r' tempi[mn] ', ' tempinho '),
    (r' to+p+a+ ', ' topa '),
    (r' a+w+ ', ' aw '), 
    (r' funcionario ', ' funcionário '),
    (r' daki ', ' daqui '),
    (r' cmg ', ' comigo '),
    (r' policia ', ' polícia '),
    (r' vicio ', ' vício '),
    (r' demais ', ' d+ '), 
    (r' d\++ ', ' d+ '),
    (r' falo+[uw]* ', ' falou '),
    (r' i+x+ ', ' vixe '),
    (r' rolo+ ', ' rolou '),
    (r' kralho+ ', ' caralho '),
    (r' peao ', ' peão '),
    (r' qts ', ' quantos '),
    (r' instantane ', ' instantâneo '),
    (r' fa+co+ ', ' faço '),
    (r' senao ', ' senão '),
    (r' qndo ', ' quando '),
    (r' n[eé]+h* ', ' né '),
    (r' n+[óo]+i+s+ ', ' nóis '),
    (r' dnvo ', ' de novo '),
    (r' i+x+[ei]+ ', ' vixe '),
    (r' versao ', ' versão '),
    (r' entao ', ' então '),
    (r' vdd ', ' verdade '),
    (r' fds ', ' fim de semana '),
    (r' ae+w+ ', ' ae '),
    (r' mt+ ', ' muito '),
    (r' f+a*l+a+ ', ' fala '),
    (r' f+d+p+ ', ' filho da puta '), 
    (r' noia+ ', ' nóia '),
    (r' sardin ', ' sardinha '),
    (r' b+l+z+ ', ' beleza '),
    (r' nuum ', ' não '),
    (r' possivel ', ' possível '),
    (r' memo ', ' mesmo '),
    (r' bebado ', ' bêbado'), 
    (r' ah+ ', ' ah '), 
    (r' ei+[mn]+ ', ' hein '), 
    (r' joguin ', ' joguinho '),
    (r' kc+t+ ', ' kct '), 
    (r' me+u+ ', ' meu '),
    (r' yt ', ' youtube '), 
    (r' kiança ', ' criança '),
    (r' mi+n+a+s+ ', ' minas '),
    (r' [eé]+h+ ', ' é '),
    (r' go+s+t+a+ ', ' gosta '),
    (r' aposento+ ', ' aposentou '),
    (r' donde ', ' da onde '), 
    (r' morremo+ ', ' morremos '),
    (r' b+l+a+u+ ', ' bláu '),
    (r' pega+mo ', ' pegamos '), 
    (r' n[uú]+[oóô]+ ', ' nuuu '),
    (r' issai ', ' isso aí '),
    (r' pare+c+e+ ', ' parece '),
    (r' mecanica ', ' mecânica '), 
    (r' mecanicas ', ' mecânicas '),
    (r' n+[aã]*o* ', ' não '),
    (r' nu+m va+i+ ', ' não vai '), 
    (r' m+u+i+t+o+ ', ' muito '),
    (r' m+t+o+ ', ' muito '),
    (r' junto+ ', ' junto '),
    (r' dissae+ ', ' disso aí '),
    (r' issae+ ', ' isso aí '),
    (r' bo+a+ ', ' boa '),
    (r' e+h+ ', ' é '),
    (r' ja+h+ ', ' já '),
    (r' fo+i+ ', ' foi '),
    (r' qu[eé]+h* ', ' quer '),
    (r' vc ', ' você '),
    (r' vcs ', ' vocês '),
    (r' ceis ', ' vocês '), 
    (r' c+t+z ', ' certeza '),
    (r' facil ', ' fácil '),
    (r' dnovo ', ' de novo '), 
    (r' f+l+w+ ', ' flw '), 
    (r' mes ', ' mês '),
    (r' zuado ', ' zoado '),
    (r' doq ', ' dq '), 
    (r' bauiu ', ' bagulho '),
    (r' agua ', ' água '), 
    (r' delicia ', ' delícia '), 
    (r' fl+o+u+ ', ' flw '),
    (r' algu[ée]+m+ ', ' alguém '),
    (r' judio+ ', ' judiou '),
    (r' v[aá]+i+ ', ' vai '),
    (r' t[aá]+ ', ' tá '),
    (r' tb+ ', ' também '),
    (r' po+[hr]+a+ ', ' porra '),
    (r' mui[ée]h? ', ' mulher '),
    (r' msmo* ', ' mesmo '),
    (r' e+ita ', ' eita '),
    (r' pqp+ ', ' pqp '),
    (r' n+u+o+s+ ', ' nossa '),
    (r' n+o+s+a+ ', ' nossa '),
    (r' se+x+t+o+u* ', ' sextou '), 
    (r' e+n+t+r+o+u+ ', ' entrou '),
    (r' s+i+m+ ', ' sim '),
    (r' v+i+x+i* ', ' vixe '),
    (r' o+w+ ', ' ow '),
    (r' rita+ ', ' rita '),
    (r' fu+nfa ', ' funciona '),
    (r' t+e+i*m+ ', ' tem '),
    (r' fo+g+e+ ', ' foge '),
    (r' ex+a+t+o+ ', ' exato '),
    (r' q+u+e+r+i+a+ ', ' queria '),
    (r' al[ií]+ ', ' ali '), 
    (r' atoa ', ' a toa '),
    (r' issaqui ', ' isso aqui '),
    (r' b+r+a+b+a+ ', ' brava '),
    (r' b+r+a+b+o+ ', ' bravo '), 
    (r' flar ', ' falar' ), 
    (r' cel ', ' celular '),
    (r' [ée]{3,} ', ' eee '),
    (r' re+n+d+e+u+ ', ' rendeu '),
    (r' u{3,} ', ' uuu '), 
    (r' mito+u* ', ' mito '),
    (r' sho+w+ ', ' show '),
    (r' de+x+o+ ', ' deixou '),
    (r' dete+s+t+o+ ', ' detesto '),
    (r' nd+ ', ' nada '),
    (r' na+da+ ', ' nada '), 
    (r' preci+sa+ ', ' precisa '),
    (r' iri+a+ ', ' iria '),
    (r' fica+r[uo]+ ', ' ficaram '),
    (r' deliça ', ' delícia '),
    (r' a+i+ ', ' ai '), 
    (r' r+l+x+ ', ' relaxa '),
    (r' ago+ra+ ', ' agora '),
    (r' hj ', ' hoje '), 
    (r' h+e+n+r+i+q+u+e+ ', ' henrique '),
    (r' podi+a+ ', ' podia '),
    (r' ehi[mn] ', ' hein '),
    (r' he+i+[mn]+ ', ' hein '), 
    (r' qd ', ' quando '),
    (r' l+o+u*[ck]+o+ ', ' louco '),
    (r' bo+u*a+ ', ' boa '),
    (r' o{3,} ', ' ooo '), 
    (r' o+p+a+ ', ' opa '),
    (r' fa+la+ ', ' fala '),
    (r' to+ ', ' estou '), 
    (r' o+l+o+u*k+o+ ', ' oloko '),
    (r' pufav[oô]+ ', ' por favor '),
    (r'  +', ' ')] 

